from backend.prompts.intent import (
    INTENT_SYSTEM_PROMPT,
    INTENT_USER_TEMPLATE,
    PIPELINE_SYSTEM_PROMPT,
    PIPELINE_USER_TEMPLATE,
)
from backend.prompts.confirmation import CONFIRMATION_CLASSIFIER_SYSTEM_PROMPT
from backend.prompts.transaction import TRANSACTION_AGENT_SYSTEM_PROMPT
from backend.prompts.qa import QA_SYSTEM_PROMPT, QA_USER_TEMPLATE
from backend.prompts.fraud_report import (
    FRAUD_REPORT_SYSTEM_PROMPT,
    FRAUD_REPORT_USER_TEMPLATE,
    FRAUD_RISK_CHECK_SYSTEM_PROMPT,
)
from backend.prompts.finance_advice import FINANCE_CHAT_SYSTEM_PROMPT

__all__ = [
    'INTENT_SYSTEM_PROMPT',
    'INTENT_USER_TEMPLATE',
    'PIPELINE_SYSTEM_PROMPT',
    'PIPELINE_USER_TEMPLATE',
    'CONFIRMATION_CLASSIFIER_SYSTEM_PROMPT',
    'TRANSACTION_AGENT_SYSTEM_PROMPT',
    'QA_SYSTEM_PROMPT',
    'QA_USER_TEMPLATE',
    'FRAUD_REPORT_SYSTEM_PROMPT',
    'FRAUD_REPORT_USER_TEMPLATE',
    'FRAUD_RISK_CHECK_SYSTEM_PROMPT',
    'FINANCE_CHAT_SYSTEM_PROMPT',
]
