from backend.prompts.intent import INTENT_SYSTEM_PROMPT, INTENT_USER_TEMPLATE
from backend.prompts.transaction import TRANSACTION_EXTRACTOR_SYSTEM_PROMPT, TRANSACTION_USER_TEMPLATE

__all__ = ['INTENT_SYSTEM_PROMPT', 'INTENT_USER_TEMPLATE',
           'TRANSACTION_EXTRACTOR_SYSTEM_PROMPT', 'TRANSACTION_USER_TEMPLATE']
